### ISSUE TITLE
Implement CI/CD

### ISSUE THREAD

**Issue by QubitPi** [paion-data/elide-doc#2]
> [!TIP]
> 如果说一款企业级软件，除了代码和[文档](https://github.com/paion-data/elide-doc/issues/1)，还有什么是最重要的，那就是 CI/CD 了
>
>CI/CD (**C**ontinuous **I**ntegration/**C**ontinuous **D**elivery) 是软件进行迭代和部署的必备组成部分。CI/CD 分成两个部分：
> 
> 1. CI: 每一个提交的 PR 都会自动触发软件的自动化测试，确保哪怕只是一行代码的修改，都不会影响软件的质量
> 2. CD: 当 PR 合并到 `master` 分支主线后，会再次自动触发软件的 CI，并且在测试通过之后，触发软件部署。在 elide-doc 这个项目中，“软件的部署”定义为”文档发布到 [GitHub Pages](https://paion-data.github.io/elide-doc/)“

目标
---

用 [GitHub Actions](https://github.com/features/actions) 实现 Elide 文档的 CI/CD

实现步骤
-------

1. 新建分支
2. 在项目根目录下创建一个名为 `.github` 的文件夹
3. 在 `.github` 文件夹下创建一个名为 `workflows` 的子文件夹
4. 在 `workflows` 文件夹下创建一个名为 `ci-cd.yml` 的GitHub Action 配置文件，内容大致为：

   ```yaml
   # Copyright Paion Data
   ---
   name: CI/CD

   'on':
     pull_request:
     push:
       branches:
         - master

   jobs:
     documentation-build:
       name: Tests Homepage Build
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v3
         - uses: ruby/setup-ruby@v1
           with:
             ruby-version: '3.0'
         - run: |
             gem install jekyll
             bundle install
             bundle exec jekyll build
   ```

5. 提交 Pull Request

> [!CAUTION]
> 上面的配置文件拷取自[另一个也是用 jekyll 做文档的项目](https://github.com/QubitPi/screwdriver-cd-homepage/blob/master/.github/workflows/ci-cd.yml#L1-L26)，但请同学学习理解上述语法(可参照 [GitHub Actions 文档](https://docs.github.com/en/actions))，确保在这个项目中不出错
